# Site settings
title: Association des sages femmes de normandie
email: sage.femme.normandie@gmail.com
description: Connaître et trouver une sage femme en Normandie

baseurl: ""
#url: "http://sagefemmenormandie.github.io"
github_username:  SageFemmeNormandie
#0Ao5u1U6KYND7dFVkcnJRNUtHWUNKamxoRGg4ZzNiT3c

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

gdrive:
  sheet: "Adhérents"
  cache_period: 1 minutes
