# Site settings
title: "Association des sages-femmes libérales de Normandie : Rouen, Le Havre, Bernay, Fécamp…"
email: sage.femme.normandie@gmail.com
description: Trouver et découvrir les activités d'une sage-femme libérale en Normandie

baseurl: ""
#url: "http://sagefemmenormandie.github.io"
github_username:  SageFemmeNormandie
#0Ao5u1U6KYND7dFVkcnJRNUtHWUNKamxoRGg4ZzNiT3c


# Build settings
markdown: kramdown

#data_dir: data

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

sass:
  sass_dir: _sass
  style: compressed

collections:
  activities:
    output: true
    order: date asc
    permalink: /:path/
    sitemap: false

defaults:
  - scope:
      path: ""
      type: activities
    values:
      layout: page

# Plugin: jekyll-assets
assets:
  sources:
    - assets/js
    - assets/css
    - assets/images
    - assets/fonts
    - _sass
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]
  compress:
    css: true
    js: true

# Plugin: data from gdrive
gdrive:
  sheet: "Adhérents"
  cache_period: 1 minutes

# Plugin: generate pages from Yaml
page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: 'members'
    template: 'profile'
    name: 'nom_entier'
    dir: ''

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-assets
